version: "3.9"

services:

  # -------------------------
  # APPLICATION (Spring Boot)
  # -------------------------
  application:
    image: shaikmustafa/deepika:app
    ports:
      - "1111:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devopsdb:3306/mydb
      SPRING_DATASOURCE_USERNAME: accounts
      SPRING_DATASOURCE_PASSWORD: devopspassword

      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq

      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080

    networks:
      - mynetwork

    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

    depends_on:
      - devopsdb
      - redis
      - rabbitmq


  # -------------------------
  # MYSQL DATABASE
  # -------------------------
  devopsdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  # -------------------------
  # REDIS (SESSION STORE)
  # -------------------------
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    deploy:
      replicas: 1


  # -------------------------
  # RABBITMQ
  # -------------------------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork
    deploy:
      replicas: 1


networks:
  mynetwork:
    driver: overlay


volumes:
  dbdata:
